# Generated by Django 5.2.11 on 2026-02-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(max_length=128, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('profile_photo_url', models.URLField(blank=True)),
                ('interests', models.JSONField(default=list)),
                ('streak_days', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
            ],
        ),
    ]
