# Generated by Django 5.1.1 on 2026-03-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_last_activity_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_activity_date',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_lang',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
