# Generated by Django 5.1.1 on 2026-03-04 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('users', '0003_userprofile_last_activity_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='lessons.lesson')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='users.userprofile')),
            ],
            options={
                'unique_together': {('profile', 'lesson')},
            },
        ),
    ]
