# Generated by Django 5.1.1 on 2026-03-04 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_userprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'order')},
        ),
    ]
