# Generated by Django 5.1.1 on 2026-03-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_options_alter_lesson_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='exercise',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
